### ISSUE TITLE
Does not work Sonoma 

### ISSUE THREAD

**Issue by thegoldknight** [breitnw/micromusic#2]
Does not display song or anything, just shows a blank screen with "not playing"

Player controls do work though

**Comment by breitnw** [comment]
Are you listening to something from your library or something on streaming? If it's on streaming I've been having that issue too in certain cases, I'm guessing it's caused by a recent macOS update. 

If you're on the release version and not the most recent commit it could also be an issue with Apple renaming "loved" to "favorited" in the API for some reason. I'll try to get an updated binary out soonish, I completely forgot to do that when I fixed it 😅

**Comment by thegoldknight** [comment]
I'm playing downloaded music through the Apple Music subscription, but it doesn't work on local files either. 
I'm on the latest release. 
Would it also be possible to add the feature where the app to stays in front of other windows even when it's not focused on it, like the original Apple Music miniplayer?

**Comment by breitnw** [comment]
Yep, that should be the problem. I'll get that fixed as soon as I can.

Also, I do like the idea of having the window stay in front, but I'd like to make a settings pane at the very least so that the user has the option. Would you mind opening another issue for that so that I can resolve them separately?

**Comment by breitnw** [comment]
I've released a new version that addresses this issue :) Will take a look at adding a settings pane next

**Comment by thegoldknight** [comment]
Hey, I downloaded the new release but now the app doesn't even launch. When I open it, I see a little blip showing the app opening on the dock for half a second, and then it disappears.
